version: '3.8'
networks:
  babylon-api-net:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PWD: ${DB_PASSWORD}
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_DATABASE}
    env_file:
      - .env
    networks:
      - babylon-api-net
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - babylon-api-net
